[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"


[[bin]]
name = "aoc3"
path = "src/aoc3.rs"

[[bin]]
name = "aoc4"
path = "src/aoc4.rs"
